version: 1
disable_existing_loggers: False

formatters:
  message:
    format: '%(message)s'
  simple:
    format: '%(levelname)s:   %(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(levelname)s:   %(asctime)s - %(name)s -  %(message)s [in %(pathname)s:%(lineno)d]'
    

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  sql_server:
    class: app.logging_config.SQLServerHandler
    level: INFO
    formatter: message

  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: app.dev.log

loggers:
  dev:
    level: DEBUG
    handlers: [sql_server, console]
    propagate: no

  prod:
    level: INFO
    handlers: [sql_server, console]
    propagate: no

root:
  level: WARNING
  handlers: [console]
